apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: dev
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: webapp
  - protocol: TCP
    port: 9999
    targetPort: 9999
    name: bindshell

---
apiVersion: v1
kind: Service
metadata:
  name: monitoring-service
  namespace: monitoring
spec:
  selector:
    app: monitoring-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: webapp
  - protocol: TCP
    port: 9999
    targetPort: 9999
    name: bindshell