apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-insecure-config
  namespace: annacon
  labels:
    app: demo-app-insecure-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app-insecure-config
  template:
    metadata:
      labels:
        app: demo-app-insecure-config
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
      - name: demo-app-insecure-config
        image: larslefebvre/h4cking-workshop-demo-app:867361
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host
          name: noderoot
      serviceAccountName: demo-app-insecure-config
      volumes:
      - name: noderoot
        hostPath:
          path: /